# Use a base image for your frontend (e.g. Node.js)
FROM node:14

# Set the working directory
WORKDIR /web

# Copy the code to the container
COPY . .

# Install the required packages
RUN npm install

EXPOSE 3000

# Run the frontend application
CMD ["npm", "run", "start"]
